services:
  sharelatex:
    restart: always
    image: sharelatex/sharelatex
    container_name: sharelatex
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - "8080:80"
    stop_grace_period: 60s
    volumes:
      - ./data:/var/lib/overleaf
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      OVERLEAF_APP_NAME: Overleaf Community Edition
      OVERLEAF_MONGO_URL: mongodb://mongo/sharelatex
      OVERLEAF_REDIS_HOST: redis
      REDIS_HOST: redis
      ENABLED_LINKED_FILE_TYPES: 'project_file,project_output_file'
      ENABLE_CONVERSIONS: 'true'
      EMAIL_CONFIRMATION_DISABLED: 'true'
      SANDBOXED_COMPILES: 'false'
      SANDBOXED_COMPILES_HOST_DIR_COMPILES: '/home/user/sharelatex_data/data/compiles'
      SANDBOXED_COMPILES_HOST_DIR_OUTPUT: '/home/user/sharelatex_data/data/output'
      SIBLING_CONTAINERS_ENABLED: 'false'
      DOCKER_RUNNER: ''
      SANDBOXED_COMPILES_SIBLING_CONTAINERS: 'false'
      OVERLEAF_ALLOW_PUBLIC_REGISTRATION: 'true'
      OVERLEAF_ALLOW_ANONYMOUS_READ_AND_WRITE_SHARING: 'true'
      OVERLEAF_ADMIN_EMAIL: 'me@checcoconf.it'
      OVERLEAF_LEGACY_REGISTER_PAGE: 'true'

  mongo:
    image: mongo:6.0
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-init-replica/init-replica.js:/docker-entrypoint-initdb.d/init-replica.js:ro
      - mongo-data:/data/db
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    restart: unless-stopped
    image: redis:6.2
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ~/redis_data:/data

volumes:
  mongo-data:
