services:
  sharelatex:
    restart: always
    image: sharelatex/sharelatex
    container_name: sharelatex
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - 8000:80
    stop_grace_period: 60s
    volumes:
      - ./data:/var/lib/overleaf
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      OVERLEAF_APP_NAME: Overleaf Community Edition
      OVERLEAF_MONGO_URL: mongodb://mongo/sharelatex
      OVERLEAF_REDIS_HOST: redis
      REDIS_HOST: redis
      ENABLED_LINKED_FILE_TYPES: 'project_file,project_output_file'
      ENABLE_CONVERSIONS: 'true'
      EMAIL_CONFIRMATION_DISABLED: 'true'
      SANDBOXED_COMPILES: 'false'
      SANDBOXED_COMPILES_HOST_DIR_COMPILES: '/home/user/sharelatex_data/data/compiles'
      SANDBOXED_COMPILES_HOST_DIR_OUTPUT: '/home/user/sharelatex_data/data/output'
      SIBLING_CONTAINERS_ENABLED: 'false'
      DOCKER_RUNNER: ''
      SANDBOXED_COMPILES_SIBLING_CONTAINERS: 'false'
      OVERLEAF_ALLOW_PUBLIC_REGISTRATION: 'true'
      OVERLEAF_ALLOW_ANONYMOUS_READ_AND_WRITE_SHARING: 'true'
      OVERLEAF_ADMIN_EMAIL: 'me@checcoconf.it'
      OVERLEAF_LEGACY_REGISTER_PAGE: 'true'

  mongo:
    image: mongo:6.0
    command: mongod --replSet overleaf --bind_ip_all
    volumes:
      - ./data/db:/data/db
      - ./mongo-init-replica/init-replica.js:/docker-entrypoint-initdb.d/mongo-init-replica.js
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping').ok === 1 && rs.status().ok === 1 ? 'ok' : 'error'"]
      interval: 15s
      timeout: 15s
      retries: 10
      
  redis:
    restart: always
    image: redis:6.2
    container_name: redis
    volumes:
      - ~/redis_data:/data
